### ISSUE TITLE
Precompiled binary for 0.1.3 fails to launch on Windows 10

### ISSUE THREAD

**Issue by adamltaylor** [takashi310/VVD_Viewer#1]
I downloaded the precompiled binary for Windows at:

https://github.com/takashi310/VVD_Viewer/releases/download/0.1.3/VVDViewer051519-win64.zip

unzipped it to a folder under my home folder, and tried to run VVDViewer.exe.

I was immediately confronted with the following dialog box:

![image](https://user-images.githubusercontent.com/2151120/59057518-8ae8ce00-8868-11e9-8348-a4b13c96c97f.png)

This is on a Windows 10 Professional box, version 10.0.17763.

The video card is an NVIDIA GeForce GTX Titan X.  Under Device Manager > Display Adapters > NVIDIA GeForce GTX TitanX > Driver > Driver Details, I see (among others):

C:\WINDOWS\system32\nvopencl.dll
C:\WINDOWS\SysWow64\nvopencl.dll
nv_desktop_ref4wu.inf_amd64_d666a2459eba14a6\OpenCL32.dll
nv_desktop_ref4wu.inf_amd64_d666a2459eba14a6\OpenCL64.dll

So it seems like at least *some* OpenCL drivers are installed.

**Comment by takashi310** [comment]
Have you tried to update your graphics driver?
It may resolve this issue.

**Comment by adamltaylor** [comment]
OK, a graphics driver update fixed it.  The old driver was from 12/2018, which didn't seem *that* old.  Sorry for the bother.

**Comment by takashi310** [comment]
No worries!
