### ISSUE TITLE
Add support for Stanford ply mesh format

### ISSUE THREAD

**Issue by jefferis** [takashi310/VVD_Viewer#3]
Hello, thank you @takashi310 for your nice work on VVD. I was wondering if it might be possible to add support for reading the Stanford ply mesh format. It is a simple binary format, more compact than obj and very widely used. There are one file header only readers if you wanted e.g. https://github.com/nmwsharp/happly https://github.com/ddiakopoulos/tinyply or perhaps https://github.com.cnpmjs.org/vilya/miniply which is two files but might be the best for simple reading.

**Comment by jefferis** [comment]
Just to add that in addition to the smaller size, there is also the advantage of faster loading. For example today I was viewing 12 meshes from EM data. 
  * Size: 412.8 MB in obj, 197.5MB in ply.
  * Load time in R: 20s obj (using [tinyojloader](https://github.com/tinyobjloader/tinyobjloader)), 5 s ply
  * Load time in VVD: 25s obj.

**Comment by takashi310** [comment]
Sorry for my late response. I implemented a ply file loader on VVDViewer. I used https://github.com/nmwsharp/happly.
The ply format is supported on the latest version (1.2.1).
I appreciate your suggestion.

**Comment by jefferis** [comment]
That's great. Thank you very much. I look forward to trying this out.
