### ISSUE TITLE
h5j project reloading

### ISSUE THREAD

**Issue by JiajunZhang-neu** [takashi310/VVD_Viewer#5]
Dear Takashi,

I found recently that the h5j format used in Janelia can save quite a lot of disk space and time for VVDviewer to load. However, whenever I tried to reopen a .vrp file containing h5j data inside, VVDviewer crashed. Could you please help to have a look on that issue?

Cheers,
Jiajun

**Comment by takashi310** [comment]
I am sorry for my late reply. I will look into it.

**Comment by JiajunZhang-neu** [comment]
Thank you very much!

**Comment by takashi310** [comment]
I fixed the H5J loader. The HDF5 library used for loading H5J files was not thread safe.
I uploaded the fixed version.
https://github.com/takashi310/VVD_Viewer/releases/tag/1.4.4
Please try this.

**Comment by JiajunZhang-neu** [comment]
It works pretty well now! Great work. Thank you very much!
